### ISSUE TITLE
Improve search for /browse

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#10]
Split tokens by whitespace and show feeds that contain all search terms (just not necessarily in order)

E.g. searching for

achd ramp

would include feeds from

ACHD - Lawrenceville (v4) RAMP

and searching for 

achd pm

would include feeds from

Lawrenceville ACHD PM25B_UG_M3

**Comment by lzmunch** [comment]
It seems like there used to be the ability to filter the types of channels to show, but that is now gone. See the help sheet: https://docs.google.com/document/d/18IFx6Tyv0EGenEpOrexnB1ajQEBYHsWWpN5wi7PPXC0/pub

**Comment by chrisbartley** [comment]
Yes, filters are currently hidden. See https://github.com/CMU-CREATE-Lab/esdr/issues/8#issuecomment-464864622

**Comment by dognotdog** [comment]
with 09986f4a5231c79fa6a34d462e9ba0960f432765 searchJSON() is back to O(n) complexity, and additionally
- searches the feed ID field
- finds the channel label `device name (feedId).channelName` as displayed in the results and plot pane, so that it can be pasted into the search field
