### ISSUE TITLE
Can we minimize the impact of paging search results on /browse?

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#11]
It's easy to not realize you're missing results on the lower left pan.

How important is it to page -- could we always show all results?  

Or could we start with and page by 10K or 25K results at a time instead of 100?  Could we place the "Load next N" button at the bottom of the list when you've scrolled to the end, and make it less greyed-out looking?

**Comment by chrisbartley** [comment]
Temporary solution is to just load 10K results at a time. See commit 33836735e1cbadaf6a64da88d42671ead05be97b
