### ISSUE TITLE
View Histogram broken on /browse with Safari

### ISSUE THREAD

**Issue by dognotdog** [CMU-CREATE-Lab/esdr#16]
Safari on macOS 10.14 seems to do this:
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/1443151/95373800-7dec4c80-08ab-11eb-9979-dccc733cd0ee.png">
instead of showing the histogram overlayed to the map as Chrome does.

**Comment by chrisbartley** [comment]
Obsolete since /browse was replaced by /explore, which then moved to environmentaldata.org.
