### ISSUE TITLE
Export link goes to foo.bar

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#20]
To reproduce:

Visit https://esdr.cmucreatelab.org/explore/#channels=3544.TEMP&plotHeight=5.000&plotAreaHeight=40.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=41.182594536015834,-79.0417042070809&zoom=8

Click on export button

Click on CSV

Browser tries to navigate to foo.bar

Screenshot.  (For this screenshot, my mouse was hovering over the CSV link, even though the mouse isn't visible.  See the URL foo.bar in the lower left)

![image](https://user-images.githubusercontent.com/324851/100950030-788d3600-34d9-11eb-9d87-a82ae8304295.png)

**Comment by rsargent** [comment]
Related, JSON link goes to esdr.cmucreatelab.org/explore:

(mouse was hovering over JSON link)
![image](https://user-images.githubusercontent.com/324851/100950155-c144ef00-34d9-11eb-8f10-a0d3bb5bd9aa.png)

**Comment by rsargent** [comment]
To reproduce this for the most recent codebase,

Visit https://environmentaldata.org/#channels=1.BP_MM_HG&plotHeight=5.000&plotAreaHeight=40.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=45.58184804624772,-79.9959&zoom=5

Click download

Observe bad URLs for CSV and JSON

Note that if you pan or zoom even a tiny bit, the URLs look to become correct.

**Comment by dognotdog** [comment]
should be fixed as of e63eff7, which makes sure download links are updated when showing the download pane.

**Comment by dognotdog** [comment]
I was wrong, it's still out of sync if the timeline has not been moved... at least that's a clue!

**Comment by dognotdog** [comment]
I am hopeful 544d56a does the trick!

**Comment by rsargent** [comment]
Fixed, thanks!!
