### ISSUE TITLE
/explore:  After you select a timezone for export, it looks unchangeable

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#22]
To repro:
Click export icon
Select any timezone
Click elsewhere
Go back to look at the timezone.  You have to delete with the keyboard to see more timezone options.

**Comment by dognotdog** [comment]
The joy of combo boxes! The HTML ones are absolutely terrible on all platforms. A hierarchical pop-up might work better, but I haven't had time to look into that, yet.

**Comment by rsargent** [comment]
Fixed!  Thanks!
