### ISSUE TITLE
/explore: easy to end up lost and with a nonsensically large bounds

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#26]
I ended up here:
https://environmentaldata.org/#channels=26074.CO&time=-3820952961785271808.000,1090768809280040448.000&cursor=1607026024.903&plotHeight=5.000&plotAreaHeight=40.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=40.47885813527241,-80.05662459280768&zoom=13

with no time axis visible:
![image](https://user-images.githubusercontent.com/324851/101082414-695dc500-3579-11eb-92f6-3ec65502f7f4.png)

and can't seem to get out by clicking day/month/year or minus on the slider.

Consider constraining time bounds to be sensible, for now, say between 1950 and 2021, at least until we can think of a more principled fix.

**Comment by rsargent** [comment]
For me on a mac with a mighty mouse with a ball, about one second of zoomout is all it takes to jump out far enough to lose the time legend.  Perhaps we should also zoom more slowly?

**Comment by dognotdog** [comment]
I'll limit the zoom when zooming out, it is already limited when zooming in.

**Comment by dognotdog** [comment]
fixed in d0d0b98 by setting the maximum scale to half a month per pixel
