### ISSUE TITLE
/explore:  search should require all terms

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#27]
Searching for liberty so2 shows:

![image](https://user-images.githubusercontent.com/324851/101082951-48e23a80-357a-11eb-8d49-5e27c2f16945.png)

It should only show feeds for which all search terms are present.

**Comment by dognotdog** [comment]
should be working with an AND search as of afb193e

**Comment by rsargent** [comment]
Works, thanks!
