### ISSUE TITLE
/explore: sparklines setting not honored

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#28]
It appears to be inverted?

![image](https://user-images.githubusercontent.com/324851/101083081-75965200-357a-11eb-8cfe-3a9eefa903d5.png)

![image](https://user-images.githubusercontent.com/324851/101083136-88a92200-357a-11eb-9c6d-27c9403f85a8.png)

**Comment by dognotdog** [comment]
should be fixed with e781cc5
