### ISSUE TITLE
/explore: wrong channel name in search results

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#31]
channel name and channel label are confused in search results, resulting in garbage for the data source's channel name

**Comment by dognotdog** [comment]
should be fixed in aab2934

**Comment by rsargent** [comment]
I don't know how to test this.  @dognotdog can you close if you see that it's fixed?

**Comment by dognotdog** [comment]
@rsargent if you can click a channel when having something in the searchbox, and the graph shows up, it's working.

**Comment by rsargent** [comment]
Thanks, confirming the fix.
