### ISSUE TITLE
/explore: Google maps markers interfere with feed markers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#46]
Splitting from #30: ... what do you think about disabling the pointer that shows up for POI on the google maps base layer? You can easily do this via this maps flag: clickableIcons: false Let cursor changes to distract the user with.

If there's a google map icon and a feed marker in the same spot, the feed marker highlights as you get the mouse close, but clicking doesn't seem to do anything.  It looks like the click is captured by the google map icon.  (And because the google map icon doesn't display anything on click, it feels to the user like the click is being ignored).

https://environmentaldata.org/#time=1606562250.922,1607167050.922&cursor=1607167050.922&plotHeight=5.000&plotAreaHeight=20.000&showFilters=true&showSettings=true&showResults=true&center=40.46477515471091,-79.95962671493909&zoom=15&search=lawrenceville+sonic

![image](https://user-images.githubusercontent.com/324851/101241284-97025580-36c2-11eb-8df9-f876d71669aa.png)

The workaround is to find a spot far from the google maps icon where the feed marker is still highlit, or to zoom in until hopefully there's more location difference between the markers.

**Comment by dognotdog** [comment]
The map is already styled, so  we just need to find out what the switch is for turning off the markers, as I don't think they're necessary on this map?

**Comment by dognotdog** [comment]
I've found out that `event.pixel` is missing from the click event when a marker is clicked, which is what the map overlay worked off, so a click on a google marker would actually cause a JS exception in the overlay.

However, `event.latLng` seems to be universally available, so switching to that seems like a good idea.

@rsargent it still seems like showing POI markers should be disabled, as they are more of a distraction than useful.

**Comment by rsargent** [comment]
Removing POIs is fine with me.

**Comment by pdille** [comment]
So I personally think we should keep POI but just make the cursor to click them go away, so it does not interfere with our own sensor clicks. It is useful to quickly see where schools, hospitals, etc are on the map.

`clickableIcons: false`

will solve this for us.

**Comment by dognotdog** [comment]
f31135a implements @pdille's suggestion.
