### ISSUE TITLE
/explore: Make red marker ring more prominent

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#50]
It's hard to see the red ring around one of the Avalon stations here:
https://environmentaldata.org/#channels=1.H2S_PPM&time=1599387529.154,1599926466.987&plotHeight=5.000&plotAreaHeight=20.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=40.499745638482445,-440.0712556043752&zoom=19&mapOnly=true
![image](https://user-images.githubusercontent.com/324851/101241558-2a3c8a80-36c5-11eb-96e1-ef9ca3fcc8a8.png)

If you zoom out, it's impossible:
https://environmentaldata.org/#channels=1.H2S_PPM&time=1599387529.154,1599926466.987&plotHeight=5.000&plotAreaHeight=20.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=40.50277441746928,-440.0746632616233&zoom=12&mapOnly=true
![image](https://user-images.githubusercontent.com/324851/101241569-43453b80-36c5-11eb-9a11-c659b351d291.png)

Consider drawing the red ring with thicker line and also drawing on top so it doesn't get buried.

**Comment by dognotdog** [comment]
see #29
