### ISSUE TITLE
/explore:  Fork /explore to a new repo

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#57]

**Comment by chrisbartley** [comment]
This looks relevant, and maybe better than a fork:

https://docs.github.com/en/free-pro-team@latest/github/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by chrisbartley** [comment]
Moving issues:

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by dognotdog** [comment]
`git subtree`-d `/public/explore` into [esdr-explorer](https://github.com/CMU-CREATE-Lab/esdr-explorer), deleted subfolders from `esdr`repo and transferrred relevant issues.
