### ISSUE TITLE
Click or double-click in browse often pans thousands of miles

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#7]
Repro:

1) Type a search in Channels, e.g. **(v4) ramp**

2) Zoom in to greater Pittsburgh area

3) Start single-clicking or double-clicking around the map

4) You'll jump to lat=0 lon=0 off the coast of Africa

Mousing around, it seems like the cursor switches from hand to arrow sometimes on the map, and it seems like clicking or double-clicking when it's arrow causes the problem.  I wonder if maybe the arrow appears when the mouse is over a sensor location that's been filtered-out by the search terms?

**Comment by chrisbartley** [comment]
Fixed in 90e9e5648d468476d7ae912196b64aab0a633e60
