### ISSUE TITLE
On browse, filtering on SO2 makes charts empty

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#8]
Repro:

1) Search for (v4) ramp

2) Turn on Search Result Filter SO2

3) Zoom into Clairton

4) Click on Clairton Center (v4) RAMP and turn on SO2

5) Observe chart at bottom does not show any data, and has title "undefined"

![image](https://user-images.githubusercontent.com/324851/52780232-bb85cd00-3017-11e9-9677-b388328ab9b8.png)

6) Turn off SO2 Search Result Filter

7) Click again on Clairton Center (v4) RAMP.  Observe that SO2 is not checked despite not being turned off by the user

![image](https://user-images.githubusercontent.com/324851/52780348-fd167800-3017-11e9-90f1-22e7fea8c03d.png)

8) Turn on (again) Clairton Center (v4) RAMP SO2

9) Observe two charts now -- the correct one with data at the bottom:

![image](https://user-images.githubusercontent.com/324851/52780417-191a1980-3018-11e9-8380-eb1f4f082d10.png)

**Comment by chrisbartley** [comment]
Temporary solution is to just hide Search Result Filters and the clear button. See commit 33836735e1cbadaf6a64da88d42671ead05be97b
